- hosts: host01
  tasks:
  - name: "Replace Title host01"
    replace: 
      path: /var/www/default/index.html
      regexp: '1'
      replace: '4'
      backup: yes

      
- hosts: host02
  tasks:
  - name: "Replace Title host02"
    replace: 
      path: /var/www/default/index.html
      regexp: '1'
      replace: '2'
      backup: yes


- hosts: host03
  tasks:
  - name: "Replace Title host03"
    replace: 
      path: /var/www/default/index.html
      regexp: '1'
      replace: '1'
      backup: yes


